### ISSUE TITLE
Lobby Pets

### ISSUE THREAD

**Issue by AlvinIsCool** [VortexCraft1/Vortex-Craft#10]
**Describe what you'd like**
What I want to clearly happen if for pets to appear, and when I mean pets I don't mean anything to do with pokemon, anyways these pets will maybe be different pets and depending on what rank you have it will give you a different pet such as a pig, horse, bee etc etc
**Server**
Where does this happen?
Hub
**Reasoning behind this**
The features are mainly actions like maybe moving side to side or doing a flip or turn, solutions can be hard because pets don't really do anything but specialize 
**Additional context**
Nothing much, but, pets are very cute and here is a tutorial and a video to give you a visual idea of what I'm thinking https://www.youtube.com/watch?v=QZAbHoLLjSo&t=76s

**Comment by VortexCraft1** [comment]
I will be looking into getting this, however it is not a priority. We will need to look into the benefits and negatives of getting this. 

I will see if we can merge it with the current GUI if we do get it.
