### ISSUE TITLE
Space References 

### ISSUE THREAD

**Issue by AlvinIsCool** [VortexCraft1/Vortex-Craft#11]
**Describe what you'd like**
So my idea for space references is maybe added some space movie references to make it feel like space and maybe people will like the references and play more, here is a list of space references you could do

1. StarWars: spaceships fighting
2. disguising as Thanos
3. Infinity stones, find every infinity stone to get the tag [Thanos]
4. Custom weapon, LightSaber
**Server**
Where does this happen?
Every server
**Reasoning behind this**
There are very much intentional reasons behind this: 1 being people will like the references and maybe roleplay a bit, 2 being, it brings the server alive, 3 being, very creative *clap *clap *clap
**Additional context**
In my opinion, this doesn't really matter but, you could add it *COULD

**Comment by VortexCraft1** [comment]
We probably will not be able to get a lightsaber without getting people to install a texture pack and with the current server set up it probably won't fit in. We may be able to get custom enchants and things that would relate to a space theme weapon but this is not a guarantee. 

Disguising as thanos, eh probably isn't too possible with a load of work and isn't a major thing at the moment. 

Infinity stones, could be a possibility to be a coupon or something. We will be looking into getting this. 

Spaceship fighting, er, not sure where or how we would implement this. It is noted as an idea.
