### ISSUE TITLE
Skyblock lobby

### ISSUE THREAD

**Issue by AlvinIsCool** [VortexCraft1/Vortex-Craft#12]
**Describe what you'd like**
What I really intend to happen with this suggestion is mostly on builds and not plugins: My suggestion includes spaceships and floating islands, but I want the owners to have wings at the front of the lobby, as a sign of respect and a skyblock themed build, and with that, maybe add some airships, and a pvp zone
**Server**
Where does this happen?
Skyblock
**Reasoning behind this**
The spaceships and floating islands are classic, and spaceships show that we are space related.  The owners with wings show respect and overall detail that we care and skyblock theming, the airships is another theme to skyblock, pvp zone is where they fight like in the old skyblock map on trovical
**Additional context**
Nothing more additional if you don't like it, don't add it, its not like I'm desperate

**Comment by VortexCraft1** [comment]
I am unsure what you mean by "wings" however, we have implemented a lot of what you have said. 
Be sure to check it out when ready.
