### ISSUE TITLE
Boss fights

### ISSUE THREAD

**Issue by Thomasvdp25060** [VortexCraft1/Vortex-Craft#14]
**Describe what you'd like**
There would be a /warp boss. This could be an arena where players fight a "boss mob". A boss spawns every 2 hours. Upon killing the boss players who participated in the fight will get a rewards. This can be money, a spawner, part of a unique kit (boss kit -> explained later). These boss mobs are mobs with custom attacks, lots of health and armor. 

Killing a boss gives you a small chance of recieving a piece of the boss kit. This is a kit that can only be obtained by these boss events. The kit contains tools, armor and weapons. I suggest lvl 6+ enchantments on these.

**Server**
Skyblock

**Reasoning behind this**
These events are the perfect opprtunity for the players to work together. None of that toxic pvp chatting! It also gives normal members a chance of getting OP gear without having to buy donor kits from ranked players.

**Additional context**
https://youtu.be/VuU_QPf_T4Q?t=759 -> idea is based off this. It's a server is used to play on a few years back.

**Comment by AlvinIsCool** [comment]
this is very nice, I would love a boss, if we had a boss, we could learn the meaning of "teamwork"

**Comment by VortexCraft1** [comment]
Yeah, I think this would be good. 

Just depends if it gets too like factions.

**Comment by AlvinIsCool** [comment]
What bosses are we gonna make? Giant Zombie? Necromancer? Fire Lord? A Beast?
possibilities are endless

**Comment by VortexCraft1** [comment]
This has been implemented by @Thomasvdp25060 
<3
