### ISSUE TITLE
Discord Channels

### ISSUE THREAD

**Issue by AlvinIsCool** [VortexCraft1/Vortex-Craft#16]
**Describe what you'd like**
Maybe we should add Emoji's on the channel names like "rules" or "announcements" on discord
**Server**
Where does this happen?
Discord Channels
**Reasoning behind this**
So the benefits in this suggestion are that we could give people a visual idea of what the channel is for other people that don't speak English or is new to English
**Additional context**
Idea's or Examples:
🔒Rules
🔊Announcments
👋Welcome
etc, etc...

**Comment by VortexCraft1** [comment]
We don't want the server overloaded with emojis. We currently have them on the sections and I find this enough.

We also do not want to run out of emojis and have them repeating. This will occur with the mass amount of channels we have.
