### ISSUE TITLE
Gun Match

### ISSUE THREAD

**Issue by AlvinIsCool** [VortexCraft1/Vortex-Craft#18]
**Describe what you'd like**
So, I've come up with this idea, which I've tried when I've owned a server, so this idea comes from the plugin crack-shot-guns, which adds guns to your server when I first found out about this plugin one idea was, gun match, which is a game where you fight people with guns and you are in a team, pretty typical, so that's my idea
**Server**
Where does this happen?
A server where there can be guns included, GunMatch
**Reasoning behind this**
The solutions or benefits of this idea, is because, well first off there are so much typical gun games and guns would be unique as it is Minecraft and guns are not available in vanilla Minecraft, so people would probably like guns and if they were in a team, they could coordinate or fight as a team such as in CSGO
**Additional context**
The plugin is called Crack Shot Guns, ask me if you need help configuring anything, or possibly need help with commands

**Comment by VortexCraft1** [comment]
Denied, at this stage we're having factions and skyblock. This suggestion would not fit in.
We may use this for future servers if we find it would be good.
